# Site settings
title: Wallit on GitHub
baseurl: 

# Build settings
markdown: kramdown
exclude: ['README.md']
sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
